services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:16.1-bookworm
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
  node_modules:
