import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Container, styled } from '../../styled-system/jsx'
import { ReactNode } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Record<'children', ReactNode>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <styled.header
          position={'sticky'}
          top="0"
          zIndex={'1'}
          py="3"
          bg="white"
          borderColor={'gray.200'}
          borderBottomWidth={'thin'}
        >
          <Container>
            <styled.h1 fontWeight={'bold'} fontSize={'lg'}>
              <Link href={'/'}>Todo App</Link>
            </styled.h1>
          </Container>
        </styled.header>
        <Container>{children}</Container>
      </body>
    </html>
  )
}
