name: Release

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

env:
  DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost/${{ secrets.POSTGRES_DB }}?schema=public&host=/cloudsql/${{ secrets.DB_CONNECTION_STRING }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-node@v4'
        with:
          node-version: 20.x
          cache: npm
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{secrets.SERVICE_ACCOUNT}}
      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      # TODO: docker build push deploy
      # - run: gcloud auth config-docker ${{ vars.REGION }}-docker.pkg.dev
      - name: Cloud SQL Auth Proxy 立ち上げ
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.6.1/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy 
          sudo mkdir /cloudsql 
          sudo chmod 777 /cloudsql
          ./cloud-sql-proxy --unix-socket /cloudsql ${{ secrets.DB_CONNECTION_STRING }} &
      - run: npx prisma migrate deploy
